routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//route pages

use App\Http\Controllers\OrganizationsController;

Route::group(['middleware' => 'admin'], function () {
    Route::get('/dashboard', 'DashboardController@index');
//route admin
});

Route::group(['prefix' => 'super', 'middleware' => 'superadmin'], function () {
    Route::get('/dashboard', 'SuperAdminController@index')->name('superadmin-dashboard');
    Route::post('/create-user', 'SuperAdminController@createUser')->name('create-user');
    
    
//route admin
});




//route authentication
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/', 'PageController@index');


Route::group(['middleware' => 'auth'], function () {

//route posts
Route::resource('posts','PostsController');

Route::resource('advertises','AdvertisementController');

Route::resource('admin','adminController');

Route::resource('customers','CustomersController');
Route::PATCH('approve/{customers}','CustomersController@approve');

Route::resource('transactions','TransactionsController');

Route::resource('branch','branchcontroller');
Route::get('/branch/create', 'branchcontroller@showBranchForm');
Route::get('/branch/edit', 'branchcontroller@showBranchForm');

Route::get('organizations','OrganizationsController@index');
Route::get('organizations/create','OrganizationsController@create');
Route::POST('organizations','OrganizationsController@store');
Route::GET('organizations/{organizations}','OrganizationsController@show');
Route::GET('organizations/{organizations}/edit','OrganizationsController@edit');
Route::PATCH('organizations/{organizations}','OrganizationsController@update');
Route::DELETE('organizations/{organizations}','OrganizationsController@destroy');


Route::GET('/init-permission', 'PermissionController@initPermission');


Route::get('/inventory', 'InventoryItemController@index');
Route::get('downloadData/{type}', 'InventoryItemController@downloadData');
Route::post('importData', 'InventoryItemController@importData');

Route::get('/stocks', 'StocksController@index');


});

Route::get('/about', 'PageController@about');
Route::get('/services', 'PageController@services');

resources/views/advertises/create.blade.php
@extends('layouts.app')

@section('content')
    <h1>Create Advertisement</h1>
    <form action ="/advertises" method = "post" enctype="multipart/form-data">

        @include('advertises.form')
        <button class ="btn btn-primary">Add Advertisement</button>

    </form>
@endsection

resources/views/advertises/edit.blade.php
@extends('layouts.app')

@section('content')
    <h1>Edit Advertisement</h1>


    <form action ="/advertisesController@update" method = "post" enctype="multipart/form-data">

        @include('advertises.form')
        <button class ="btn btn-primary">Edit Advertisement</button>
        </form>
    @endsection

resources/views/advertises/form.blade.php
{{ csrf_field() }}

<div class="mb 5">
<div class = "form-group">
        <label for ="oname">Organization Name</label>
        <input type="text" name= "oname" value="{{old('oname') ?? $advertises->oname}} " class ="form-control" placeholder="Organization Name">
        {{-- <input type="text" name= "oname" value="oname " class ="form-control" placeholder="Organization Name"> --}}
         {{$errors->first('oname')}}
    </div>
    <div class = "form-group">
        <label for ="ad_name">advertisesment Name</label>
        <input type="text" name= "ad_name" value="{{old('ad_name') ?? $advertises->ad_name}} " class ="form-control" placeholder="advertisesment Name">
         {{$errors->first('oname')}}
    </div>
    <div class = "form-group">
        <label for ="ad_message">Description</label>
        <input type="text" name= "ad_message" value="{{old('ad_message') ?? $advertises->ad_message}} " class ="form-control" placeholder="Description">
         {{$errors->first('ad_message')}}
    </div>
    <div class = "form-group">
        <label for ="ad_image">advertisesment Image </label>
        <input type="file" name ="ad_image"value ="{{old('ad_image')?? $advertises->ad_image}}" class ="form-control" placeholder="Please Upload advertisesment image">
        <div>{{$errors->first('ad_image')}}</div>
    </div>
</div>

resources/views/advertises/index.blade.php
@extends('layouts.app')

@section('content')
    <h1>Advertises</h1>
    
    <a href="{{route('advertises.create')}}">Create Advertisement</a>
    @if (count($advertises)>0)
        @foreach ($advertises as $advertise)
            <div class = "well">
            <h3><a class="advertiselink" href ="/advertises/{{$advertise->ad_id}}">{{$advertise->oname}}</a></h3>
                <small> written on {{$advertise->created_at}}</small>
            </div>
        @endforeach


      {{-- {{ $posts->links() }} --}}
    @else
        no posts found

    @endif
        


@endsection

resources/views/advertises/show.blade.php
@extends('layouts.app')

@section('title')
    Show advertisements
@endsection
@section('content')
<p><a href ={{route('advertises.index')}} class = "btn btn-primary"> Go back</a></p>
    <h3> Information about advertises</h3>
    <div class="row p-3">


    <form action = "/advertises/{{$advertises->ad_id}}/edit">
        <button class = "btn btn-primary" class="p-5">Edit</button>
    </form>
    <form action = "/advertises/{{$advertises->ad_id}}" method = "POST">
        @method('delete')
        @csrf
        <button value="delete" class="btn btn-danger">Delete</button>
    </form>
    </div>
    <br/>
    <div class="row">
        <div class="col-6">
<p><strong>ID: </strong>{{$advertises->ad_id}}</p>
<p><strong>organization Name: </strong>{{$advertises->oname}}</p>
<p><strong>advertisesment Name</strong>{{$advertises->contactno1}}</p>
<p><strong>advertisesment Message </strong>{{$advertises->contactno2}}</p>
<p><strong>Image </strong>{{$advertises->headquarter}}</p>

</div>
@if($advertises->ad_image)

<div class="row">
<div class="col-6"><img src="{{ asset('storage/' . $advertises->ad_image) }}" alt="Adv logo" height="300" width="400"></div>
</div>
</div>
@endif
@endsection